name: Python CI with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python iris_test.py

    - name: Build Docker Image
      run: docker build -t my-python-app .

